### ISSUE TITLE
Only a single waiter will ever be awoken

### ISSUE THREAD

**Issue by nagisa** [softprops/waitgroup#2]
Implementation uses `Condvar::notify_one`, which will only wake up a single thread once counter reaches 0, leaving all other waiters deadlocked.

**Comment by softprops** [comment]
Nice catch. This was roughly a counter translation of the example in the condvar docs

https://doc.rust-lang.org/std/sync/struct.Condvar.html

Looks like notify_all is what I really want

**Comment by softprops** [comment]
fixed in 363d80a2fc4f79a28753b7a03b5f62c4d5a4291e
